/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentRouteImport } from './routes/student'
import { Route as UniversitiesRouteImport } from './routes/universities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/application': typeof ApplicationRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/real-estate': typeof RealEstateRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/application': typeof ApplicationRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/real-estate': typeof RealEstateRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/application': typeof ApplicationRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/real-estate': typeof RealEstateRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accommodation'
    | '/application'
    | '/contact'
    | '/countries'
    | '/courses'
    | '/login'
    | '/marketplace'
    | '/real-estate'
    | '/scholarships'
    | '/services'
    | '/signup'
    | '/student'
    | '/universities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accommodation'
    | '/application'
    | '/contact'
    | '/countries'
    | '/courses'
    | '/login'
    | '/marketplace'
    | '/real-estate'
    | '/scholarships'
    | '/services'
    | '/signup'
    | '/student'
    | '/universities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accommodation'
    | '/application'
    | '/contact'
    | '/countries'
    | '/courses'
    | '/login'
    | '/marketplace'
    | '/real-estate'
    | '/scholarships'
    | '/services'
    | '/signup'
    | '/student'
    | '/universities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccommodationRoute: typeof AccommodationRoute
  ApplicationRoute: typeof ApplicationRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRoute
  CoursesRoute: typeof CoursesRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  RealEstateRoute: typeof RealEstateRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRoute
  UniversitiesRoute: typeof UniversitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccommodationRoute: AccommodationRoute,
  ApplicationRoute: ApplicationRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRoute,
  CoursesRoute: CoursesRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  RealEstateRoute: RealEstateRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRoute,
  UniversitiesRoute: UniversitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
